use abs. paths, exit after rsync failure, test/example adapt.

diff --git a/backupto-remote b/backupto-remote
--- a/backupto-remote
+++ b/backupto-remote
@@ -43,7 +43,7 @@ for c in "$1" "$2"; do
 done
 
 # temporary preprocessed list file
-TMP_LIST="backup-${BACKUP_PREFIX}-remote-TMP.list"
+TMP_LIST="/tmp/backup-${BACKUP_PREFIX}-remote-TMP.list"
 
 preprocess_list
 
@@ -54,6 +54,9 @@ rsync -av -r --numeric-ids --link-dest=../"$BACKUP_PREFIX"_last \
     --files-from="$TMP_LIST" \
     "$SRC_PATH_ABS" \
     "$REMOTE_USER"@"$REMOTE_HOST":"$DEST_PATH"/"$BACKUP_PREFIX"_"$DATE"
+
+# exit on failure
+if [[ "$?" -ne 0 ]]; then exit 1; fi
 
 # cleanup
 rm "$TMP_LIST"
