simplify config handling, cleanup

diff --git a/backupto-remote b/backupto-remote
--- a/backupto-remote
+++ b/backupto-remote
@@ -1,46 +1,46 @@
 #!/bin/bash
 #
 # backup list of directories/files to remote host,
-# given config files as argument
+# config file as argument
 #
-# $1 remote settings
-# $2 backup list
+# $1 settings file
+#
+# the config file shall contain the variables:
+#
+# SRC_PATH_ABS      absolute path to the files to backup, e.g. $HOME
+# BACKUP_LIST       list of files/directories to backup,
+#                   the list may contain # comments and empty lines
+#
+# BACKUP_PREFIX     backups will be in the form of PREFIX_DATE_TIME
+# DEST_PATH         destination path, can be relative
+#
+# REMOTE_HOST       remote hostname/ip addr.
+# REMOTE_USER       remote username to use for login
+#
+# ADD_RSYNC_OPT     additional rsync options, e.g. used -R used for system backup
+#
 #
 # using rsync (incremental)
 # reference:
 # - http://www.ibm.com/developerworks/aix/library/au-spunix_rsync/index.html#backup
 # found on: https://wiki.archlinux.org/index.php/Backup_programs
 #
-# the config file shall contain the variables:
-#
-# SRC_PATH_ABS      absolute path to the files to backup, e.g. $HOME
-#
-# BACKUP_LIST       list of files/directories to backup,
-#                   the list may contain # comments and empty lines
-# BACKUP_PREFIX     backups will be in the form of PREFIX_DATE_TIME
-#
-# BACKUP_PATH       destination path, can be relative
-# MOUNTPOINT        mountpoint within dest. path
-#
-# ADD_RSYNC_OPT     additional rsync options
 
 # includes
 . common_f
 
-DATE=$(date "+%Y-%m-%d_%H:%M:%S")
-
-echo "Backup start $DATE"
-
 # check args
-if [ ! $# -eq 2 ]; then
-    echo "Config files expected as argument. Leaving."
-    exit 1
-fi
+#if [ ! $# -eq 2 ]; then
+#    echo "Config files expected as argument. Leaving."
+#    exit 1
+#fi
 
-for c in "$1" "$2"; do
-    check_config_arg "$c"
-    source "$c"
-done
+check_config_arg "$1"
+source "$1"
+check_config_opts
+
+DATE=$(date "+%Y-%m-%d_%H:%M:%S")
+echo "Backup start: $DATE"
 
 # temporary preprocessed list file
 TMP_LIST="/tmp/backup-${BACKUP_PREFIX}-remote-TMP.list"
@@ -56,7 +56,11 @@ rsync -av -r --numeric-ids --link-dest=../"$BACKUP_PREFIX"_last \
     "$REMOTE_USER"@"$REMOTE_HOST":"$DEST_PATH"/"$BACKUP_PREFIX"_"$DATE"
 
 # exit on failure
-if [[ "$?" -ne 0 ]]; then exit 1; fi
+if [[ "$?" -ne 0 ]]; then
+    echo "A failure occured during rsync, exiting."
+    rm "$TMP_LIST"
+    exit 1
+fi
 
 # cleanup
 rm "$TMP_LIST"
@@ -66,4 +70,4 @@ rm "$TMP_LIST"
 ssh "$REMOTE_USER"@"$REMOTE_HOST" rm "$DEST_PATH"/"${BACKUP_PREFIX}_last"
 ssh "$REMOTE_USER"@"$REMOTE_HOST" ln -s "${BACKUP_PREFIX}_${DATE}" "$DEST_PATH"/"${BACKUP_PREFIX}_last"
 
-echo "Backup end"
+echo "Backup end."
diff --git a/common_f b/common_f
--- a/common_f
+++ b/common_f
@@ -2,14 +2,22 @@
 # common functions
 
 check_config_arg() {
-    # check arguments for config file
+    # check for config file
     if [ "${1##*.}" != "conf" ]; then
         echo "A .conf file is expected. Leaving."
         exit 1
     fi
-
     if [ ! -f "$1" ]; then
         echo "Config file not found. Leaving."
+        exit 1
+    fi
+    return
+}
+
+check_config_opts() {
+    # check config options
+    if [ ! -f "$BACKUP_LIST" ]; then
+        echo "Backup list not found, leaving."
         exit 1
     fi
     return
